log:
  level: info
  job_level: info

runner:
  file: .runner
  capacity: 4
  # envs:
    # A_TEST_ENV_NAME_1: a_test_env_value_1
    # A_TEST_ENV_NAME_2: a_test_env_value_2
  env_file: .env
  timeout: 30m
  shutdown_timeout: 30m
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s
  report_interval: 1s
  labels: []

cache:
  enabled: true
  port: 0
  dir: ""
  external_server: ""
  secret: ""
  host: ""
  proxy_port: 0
  actions_cache_url_override: ""

container:
  network: ""
  enable_ipv6: false
  privileged: false
  options:
  workdir_parent:
  valid_volumes: []
  docker_host: "-"
  force_pull: false
  force_rebuild: false

host:
  workdir_parent:
